### ISSUE TITLE
extension ui and frontend initialization

### ISSUE THREAD

**Issue by dipenkhatri7** [erwinschrodinger1/decent#1]
Create frontend ui and script prototype @bibhushansaakha

**Comment by bibhushansaakha** [comment]
Working on it @dipenkhatri7 . Recieved some ui ideas from @1shan-pixel

**Comment by bibhushansaakha** [comment]
I have added a Pull Request with initial prototype.

**Comment by bibhushansaakha** [comment]
All complete!
